[project]
name = "baml-py-hello"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "baml-py>=0.81.1",
    "fastapi[standard]>=0.115.12",
    "python-dotenv>=1.1.0",
    "python-fasthtml>=0.12.4",
]
